version: '2'
services:
    node:
        image: semi/node
        container_name: node-semisugar
        ports:
            - "3001:3000"
        environment:
            API_URl: /api/v1
            CONNECTION_STRING: mongodb+srv://semi-sugar:7789989865_Rex@cluster0.uvr70.mongodb.net/?retryWrites=true&w=majority
            DB_NAME: semi-database-prod
            DOMAIN: https://www.semisugar.ca/
            SECRET: semisemi
            SECRET_KEY_STRIPE: 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
            ENDPOINT_POINT_SECRET: whsec_f69329d9badff82b4a076446be0368ec554bd71d31357667dbf4e1881f8f857f
            PORT: 3000